CREATE TABLE CARDS (
	NAME VARCHAR (32) NOT NULL,
	REALNAME VARCHAR (32) NOT NULL,
	COST INT NOT NULL,
	TYPE VARCHAR (8) NOT NULL,
	CARDSET VARCHAR (8) NOT NULL,
	RARITY VARCHAR (6) NOT NULL,
	ASPECT VARCHAR (6) NOT NULL,
	IMAGE VARCHAR (200) NOT NULL,
	CARDTEXT VARCHAR (64),
	SUBTYPE VARCHAR (8),
	ATTACK INT,
	HEALTH INT,
	PRIMARY KEY (NAME)
);
